# Generated by Django 2.0 on 2017-12-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='游戏项目')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'gameproject',
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='游戏版本名称')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.GameProject', verbose_name='游戏项目')),
            ],
            options={
                'db_table': 'gameversion',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe_name', models.CharField(max_length=50, verbose_name='名称')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作系统')),
                ('cpu_num', models.IntegerField(default=4, verbose_name='CPU数量')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='硬盘信息')),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')),
                ('passwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='ssh端口')),
                ('asset_type', models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器'), ('4', '网络设备'), ('5', '其他')], max_length=30, null=True, verbose_name='设备类型')),
                ('status', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=30, null=True, verbose_name='设备状态')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '主机管理',
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='运营商')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Operator', verbose_name='运营商'),
        ),
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.GameProject', verbose_name='游戏项目'),
        ),
        migrations.AddField(
            model_name='host',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.GameVersion', verbose_name='版本名称'),
        ),
    ]
