# Generated by Django 2.0 on 2017-12-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='describe_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
    ]
