# Generated by Django 2.0 on 2017-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171229_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.CharField(blank=True, default='root', max_length=50, null=True, verbose_name='密码'),
        ),
    ]
